### ISSUE TITLE
解像度の問題

### ISSUE THREAD

**Issue by takpika** [takonasu/SlideBukkonuki#13]
Python版への移植が完了したため、SGOの動画を使って試してみた結果同じくエラーが発生。
main.cppの92行目にあたる部分でframe1にNoneが入力されるようです。

**Comment by takpika** [comment]
ただし、91行目のframe_num - 10を10などの固定数に変更するとエラーなしで動作するようです。
SGOの動画は1334x750 H.264 AAC mp4ファイルです。

**Comment by takonasu** [comment]
Pythonに移植したためのエラーは保証しかねます。
C++のコードをコンパイルした実行可能ファイルではそのようなエラーが出ますか？
また、解像度を1280*720等に再エンコードした場合はそのようなエラーがでるのかを確認して欲しいです。

**Comment by takpika** [comment]
C++でframe1のtypeを出力するように変更し出力を確認しましたが問題ありませんでした。Pythonとは別問題のようです。ただし同じエラーは発生しました。
ただ解像度を適当に指定して画面録画したもの(1280x806)をソフトに通したところエラーなしでした。
解像度によって結果が変わるようです。

**Comment by takonasu** [comment]
当初の開発思想が画面解像度16:9か4:9が前提だったので、そのためのC++プログラムのバグです。これに関しては僕の方で修正しておきます。

**Comment by takpika** [comment]
お願いします
